########################(beg of [Makefile])########################
MyFinalLib=./../..
###################################################################

comp::

###################################################################

clean:: ; rm -f *~

cleanall:: clean
cleanall:: ; rm -f *.class

###################################################################

comp:: ; javac -cp $(MyFinalLib) FnTupl2.java
comp:: ; javac -cp $(MyFinalLib) FnTupl2Util.java

###################################################################

comp:: ; javac -cp $(MyFinalLib) FnTupl3.java
comp:: ; javac -cp $(MyFinalLib) FnTupl3Util.java

########################(end of [Makefile])########################
