########################(beg of [Makefile])########################
MyFinalLib=./../..
###################################################################

comp::

###################################################################

clean:: ; rm -f *~

cleanall:: clean
cleanall:: ; rm -f *.class

###################################################################

comp:: ; javac -cp .:$(MyFinalLib) LnStrm.java
comp:: ; javac -cp .:$(MyFinalLib) LnStcn.java
comp:: ; javac -cp .:$(MyFinalLib) LnStrmSUtil.java

########################(end of [Makefile])########################
