########################(beg of [Makefile])########################
MyFinalLib=./../..
###################################################################

comp::

###################################################################

clean:: ; rm -f *~

cleanall:: clean
cleanall:: ; rm -f *.class

###################################################################

comp:: ; javac -cp $(MyFinalLib) FnA1sz.java
comp:: ; javac -cp $(MyFinalLib) FnA1szUtil.java
comp:: ; javac -cp $(MyFinalLib) FnA1szSUtil.java

########################(end of [Makefile])########################
